version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    links:
      - "cyclone"
      - "web"

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: docker-demo
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis

  cyclone:
    command: ./run_cyclone.sh
    build: .
    links:
      - redis
    volumes:
      - .:/srv

  web:
    command: python app.py
    build: .
    links:
      - db
      - redis
    volumes:
      - .:/srv
